// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: acgc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ACGCService_Run_FullMethodName          = "/acgc.v1.ACGCService/Run"
	ACGCService_CaptureEvent_FullMethodName = "/acgc.v1.ACGCService/CaptureEvent"
	ACGCService_GetState_FullMethodName     = "/acgc.v1.ACGCService/GetState"
	ACGCService_TriggerGC_FullMethodName    = "/acgc.v1.ACGCService/TriggerGC"
	ACGCService_GetMetrics_FullMethodName   = "/acgc.v1.ACGCService/GetMetrics"
)

// ACGCServiceClient is the client API for ACGCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ACGCServiceClient interface {
	// Full intercept-compile-forward cycle.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Capture a single event (lower-level usage).
	CaptureEvent(ctx context.Context, in *CaptureEventRequest, opts ...grpc.CallOption) (*CaptureEventResponse, error)
	// Inspect the current state tree for a session.
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// Manually trigger garbage collection for a session.
	TriggerGC(ctx context.Context, in *TriggerGCRequest, opts ...grpc.CallOption) (*TriggerGCResponse, error)
	// Get token savings and other metrics for a session.
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type aCGCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewACGCServiceClient(cc grpc.ClientConnInterface) ACGCServiceClient {
	return &aCGCServiceClient{cc}
}

func (c *aCGCServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, ACGCService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCGCServiceClient) CaptureEvent(ctx context.Context, in *CaptureEventRequest, opts ...grpc.CallOption) (*CaptureEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureEventResponse)
	err := c.cc.Invoke(ctx, ACGCService_CaptureEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCGCServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, ACGCService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCGCServiceClient) TriggerGC(ctx context.Context, in *TriggerGCRequest, opts ...grpc.CallOption) (*TriggerGCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerGCResponse)
	err := c.cc.Invoke(ctx, ACGCService_TriggerGC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCGCServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ACGCService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACGCServiceServer is the server API for ACGCService service.
// All implementations must embed UnimplementedACGCServiceServer
// for forward compatibility.
type ACGCServiceServer interface {
	// Full intercept-compile-forward cycle.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Capture a single event (lower-level usage).
	CaptureEvent(context.Context, *CaptureEventRequest) (*CaptureEventResponse, error)
	// Inspect the current state tree for a session.
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	// Manually trigger garbage collection for a session.
	TriggerGC(context.Context, *TriggerGCRequest) (*TriggerGCResponse, error)
	// Get token savings and other metrics for a session.
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedACGCServiceServer()
}

// UnimplementedACGCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedACGCServiceServer struct{}

func (UnimplementedACGCServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedACGCServiceServer) CaptureEvent(context.Context, *CaptureEventRequest) (*CaptureEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureEvent not implemented")
}
func (UnimplementedACGCServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedACGCServiceServer) TriggerGC(context.Context, *TriggerGCRequest) (*TriggerGCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerGC not implemented")
}
func (UnimplementedACGCServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedACGCServiceServer) mustEmbedUnimplementedACGCServiceServer() {}
func (UnimplementedACGCServiceServer) testEmbeddedByValue()                     {}

// UnsafeACGCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACGCServiceServer will
// result in compilation errors.
type UnsafeACGCServiceServer interface {
	mustEmbedUnimplementedACGCServiceServer()
}

func RegisterACGCServiceServer(s grpc.ServiceRegistrar, srv ACGCServiceServer) {
	// If the following call panics, it indicates UnimplementedACGCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ACGCService_ServiceDesc, srv)
}

func _ACGCService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACGCServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACGCService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACGCServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACGCService_CaptureEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACGCServiceServer).CaptureEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACGCService_CaptureEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACGCServiceServer).CaptureEvent(ctx, req.(*CaptureEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACGCService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACGCServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACGCService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACGCServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACGCService_TriggerGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerGCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACGCServiceServer).TriggerGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACGCService_TriggerGC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACGCServiceServer).TriggerGC(ctx, req.(*TriggerGCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACGCService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACGCServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACGCService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACGCServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ACGCService_ServiceDesc is the grpc.ServiceDesc for ACGCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACGCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acgc.v1.ACGCService",
	HandlerType: (*ACGCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _ACGCService_Run_Handler,
		},
		{
			MethodName: "CaptureEvent",
			Handler:    _ACGCService_CaptureEvent_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ACGCService_GetState_Handler,
		},
		{
			MethodName: "TriggerGC",
			Handler:    _ACGCService_TriggerGC_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ACGCService_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acgc.proto",
}
