// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: acgc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskId              string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserMessage         string                 `protobuf:"bytes,3,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	TokenBudget         int32                  `protobuf:"varint,4,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	Policy              string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"` // "balanced", "aggressive", "conservative"
	LlmConfig           *LLMConfig             `protobuf:"bytes,6,opt,name=llm_config,json=llmConfig,proto3" json:"llm_config,omitempty"`
	ConversationHistory []*Message             `protobuf:"bytes,7,rep,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_acgc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *RunRequest) GetTokenBudget() int32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *RunRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *RunRequest) GetLlmConfig() *LLMConfig {
	if x != nil {
		return x.LlmConfig
	}
	return nil
}

func (x *RunRequest) GetConversationHistory() []*Message {
	if x != nil {
		return x.ConversationHistory
	}
	return nil
}

type LLMConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "openai", "anthropic", "ollama", etc.
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMConfig) Reset() {
	*x = LLMConfig{}
	mi := &file_acgc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMConfig) ProtoMessage() {}

func (x *LLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMConfig.ProtoReflect.Descriptor instead.
func (*LLMConfig) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{1}
}

func (x *LLMConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system", "user", "assistant", "tool"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_acgc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type RunResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LlmResponse      string                 `protobuf:"bytes,1,opt,name=llm_response,json=llmResponse,proto3" json:"llm_response,omitempty"`
	Stats            *PromptStats           `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	CompiledPromptId string                 `protobuf:"bytes,3,opt,name=compiled_prompt_id,json=compiledPromptId,proto3" json:"compiled_prompt_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_acgc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{3}
}

func (x *RunResponse) GetLlmResponse() string {
	if x != nil {
		return x.LlmResponse
	}
	return ""
}

func (x *RunResponse) GetStats() *PromptStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *RunResponse) GetCompiledPromptId() string {
	if x != nil {
		return x.CompiledPromptId
	}
	return ""
}

type PromptStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OriginalTokenCount int32                  `protobuf:"varint,1,opt,name=original_token_count,json=originalTokenCount,proto3" json:"original_token_count,omitempty"`
	CompiledTokenCount int32                  `protobuf:"varint,2,opt,name=compiled_token_count,json=compiledTokenCount,proto3" json:"compiled_token_count,omitempty"`
	TokensSaved        int32                  `protobuf:"varint,3,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	ReductionPercent   float32                `protobuf:"fixed32,4,opt,name=reduction_percent,json=reductionPercent,proto3" json:"reduction_percent,omitempty"`
	GcTriggered        bool                   `protobuf:"varint,5,opt,name=gc_triggered,json=gcTriggered,proto3" json:"gc_triggered,omitempty"`
	GcReason           string                 `protobuf:"bytes,6,opt,name=gc_reason,json=gcReason,proto3" json:"gc_reason,omitempty"`
	ActiveNodes        int32                  `protobuf:"varint,7,opt,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	CompressedNodes    int32                  `protobuf:"varint,8,opt,name=compressed_nodes,json=compressedNodes,proto3" json:"compressed_nodes,omitempty"`
	ArchivedNodes      int32                  `protobuf:"varint,9,opt,name=archived_nodes,json=archivedNodes,proto3" json:"archived_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PromptStats) Reset() {
	*x = PromptStats{}
	mi := &file_acgc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptStats) ProtoMessage() {}

func (x *PromptStats) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptStats.ProtoReflect.Descriptor instead.
func (*PromptStats) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{4}
}

func (x *PromptStats) GetOriginalTokenCount() int32 {
	if x != nil {
		return x.OriginalTokenCount
	}
	return 0
}

func (x *PromptStats) GetCompiledTokenCount() int32 {
	if x != nil {
		return x.CompiledTokenCount
	}
	return 0
}

func (x *PromptStats) GetTokensSaved() int32 {
	if x != nil {
		return x.TokensSaved
	}
	return 0
}

func (x *PromptStats) GetReductionPercent() float32 {
	if x != nil {
		return x.ReductionPercent
	}
	return 0
}

func (x *PromptStats) GetGcTriggered() bool {
	if x != nil {
		return x.GcTriggered
	}
	return false
}

func (x *PromptStats) GetGcReason() string {
	if x != nil {
		return x.GcReason
	}
	return ""
}

func (x *PromptStats) GetActiveNodes() int32 {
	if x != nil {
		return x.ActiveNodes
	}
	return 0
}

func (x *PromptStats) GetCompressedNodes() int32 {
	if x != nil {
		return x.CompressedNodes
	}
	return 0
}

func (x *PromptStats) GetArchivedNodes() int32 {
	if x != nil {
		return x.ArchivedNodes
	}
	return 0
}

type CaptureEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "user_prompt", "llm_response", "tool_call", "tool_result", "error", "system"
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureEventRequest) Reset() {
	*x = CaptureEventRequest{}
	mi := &file_acgc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureEventRequest) ProtoMessage() {}

func (x *CaptureEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureEventRequest.ProtoReflect.Descriptor instead.
func (*CaptureEventRequest) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{5}
}

func (x *CaptureEventRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureEventRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CaptureEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CaptureEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CaptureEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CaptureEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureEventResponse) Reset() {
	*x = CaptureEventResponse{}
	mi := &file_acgc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureEventResponse) ProtoMessage() {}

func (x *CaptureEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureEventResponse.ProtoReflect.Descriptor instead.
func (*CaptureEventResponse) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CaptureEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetStateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeScores     bool                   `protobuf:"varint,2,opt,name=include_scores,json=includeScores,proto3" json:"include_scores,omitempty"`
	IncludeCompressed bool                   `protobuf:"varint,3,opt,name=include_compressed,json=includeCompressed,proto3" json:"include_compressed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_acgc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStateRequest) GetIncludeScores() bool {
	if x != nil {
		return x.IncludeScores
	}
	return false
}

func (x *GetStateRequest) GetIncludeCompressed() bool {
	if x != nil {
		return x.IncludeCompressed
	}
	return false
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Nodes         []*StateNode           `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TreeStats     *TreeStats             `protobuf:"bytes,4,opt,name=tree_stats,json=treeStats,proto3" json:"tree_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_acgc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{8}
}

func (x *GetStateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStateResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetStateResponse) GetNodes() []*StateNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetStateResponse) GetTreeStats() *TreeStats {
	if x != nil {
		return x.TreeStats
	}
	return nil
}

type StateNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "goal", "constraint", "decision", "attempt", "tool_result", "issue", "summary", "compressed_branch"
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Facts         []string               `protobuf:"bytes,6,rep,name=facts,proto3" json:"facts,omitempty"`
	Decisions     []string               `protobuf:"bytes,7,rep,name=decisions,proto3" json:"decisions,omitempty"`
	OpenIssues    []string               `protobuf:"bytes,8,rep,name=open_issues,json=openIssues,proto3" json:"open_issues,omitempty"`
	Dependencies  []string               `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	RawEventRefs  []string               `protobuf:"bytes,10,rep,name=raw_event_refs,json=rawEventRefs,proto3" json:"raw_event_refs,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"` // "active", "resolved", "stale", "compressed", "archived"
	Scores        *NodeScores            `protobuf:"bytes,12,opt,name=scores,proto3" json:"scores,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateNode) Reset() {
	*x = StateNode{}
	mi := &file_acgc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateNode) ProtoMessage() {}

func (x *StateNode) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateNode.ProtoReflect.Descriptor instead.
func (*StateNode) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{9}
}

func (x *StateNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateNode) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *StateNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *StateNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StateNode) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *StateNode) GetFacts() []string {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *StateNode) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *StateNode) GetOpenIssues() []string {
	if x != nil {
		return x.OpenIssues
	}
	return nil
}

func (x *StateNode) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *StateNode) GetRawEventRefs() []string {
	if x != nil {
		return x.RawEventRefs
	}
	return nil
}

func (x *StateNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StateNode) GetScores() *NodeScores {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *StateNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StateNode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type NodeScores struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SemanticRelevance float32                `protobuf:"fixed32,1,opt,name=semantic_relevance,json=semanticRelevance,proto3" json:"semantic_relevance,omitempty"`
	Recency           float32                `protobuf:"fixed32,2,opt,name=recency,proto3" json:"recency,omitempty"`
	DependencyWeight  float32                `protobuf:"fixed32,3,opt,name=dependency_weight,json=dependencyWeight,proto3" json:"dependency_weight,omitempty"`
	Redundancy        float32                `protobuf:"fixed32,4,opt,name=redundancy,proto3" json:"redundancy,omitempty"`
	RetentionScore    float32                `protobuf:"fixed32,5,opt,name=retention_score,json=retentionScore,proto3" json:"retention_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeScores) Reset() {
	*x = NodeScores{}
	mi := &file_acgc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScores) ProtoMessage() {}

func (x *NodeScores) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScores.ProtoReflect.Descriptor instead.
func (*NodeScores) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{10}
}

func (x *NodeScores) GetSemanticRelevance() float32 {
	if x != nil {
		return x.SemanticRelevance
	}
	return 0
}

func (x *NodeScores) GetRecency() float32 {
	if x != nil {
		return x.Recency
	}
	return 0
}

func (x *NodeScores) GetDependencyWeight() float32 {
	if x != nil {
		return x.DependencyWeight
	}
	return 0
}

func (x *NodeScores) GetRedundancy() float32 {
	if x != nil {
		return x.Redundancy
	}
	return 0
}

func (x *NodeScores) GetRetentionScore() float32 {
	if x != nil {
		return x.RetentionScore
	}
	return 0
}

type TreeStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes      int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ActiveNodes     int32                  `protobuf:"varint,2,opt,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	CompressedNodes int32                  `protobuf:"varint,3,opt,name=compressed_nodes,json=compressedNodes,proto3" json:"compressed_nodes,omitempty"`
	ArchivedNodes   int32                  `protobuf:"varint,4,opt,name=archived_nodes,json=archivedNodes,proto3" json:"archived_nodes,omitempty"`
	MaxDepth        int32                  `protobuf:"varint,5,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	MaxWidth        int32                  `protobuf:"varint,6,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TreeStats) Reset() {
	*x = TreeStats{}
	mi := &file_acgc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeStats) ProtoMessage() {}

func (x *TreeStats) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeStats.ProtoReflect.Descriptor instead.
func (*TreeStats) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{11}
}

func (x *TreeStats) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *TreeStats) GetActiveNodes() int32 {
	if x != nil {
		return x.ActiveNodes
	}
	return 0
}

func (x *TreeStats) GetCompressedNodes() int32 {
	if x != nil {
		return x.CompressedNodes
	}
	return 0
}

func (x *TreeStats) GetArchivedNodes() int32 {
	if x != nil {
		return x.ArchivedNodes
	}
	return 0
}

func (x *TreeStats) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TreeStats) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

type TriggerGCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerGCRequest) Reset() {
	*x = TriggerGCRequest{}
	mi := &file_acgc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerGCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerGCRequest) ProtoMessage() {}

func (x *TriggerGCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerGCRequest.ProtoReflect.Descriptor instead.
func (*TriggerGCRequest) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerGCRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerGCRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TriggerGCResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Triggered          bool                   `protobuf:"varint,1,opt,name=triggered,proto3" json:"triggered,omitempty"`
	NodesSwept         int32                  `protobuf:"varint,2,opt,name=nodes_swept,json=nodesSwept,proto3" json:"nodes_swept,omitempty"`
	BranchesCompressed int32                  `protobuf:"varint,3,opt,name=branches_compressed,json=branchesCompressed,proto3" json:"branches_compressed,omitempty"`
	TokensFreed        int32                  `protobuf:"varint,4,opt,name=tokens_freed,json=tokensFreed,proto3" json:"tokens_freed,omitempty"`
	Reason             string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TriggerGCResponse) Reset() {
	*x = TriggerGCResponse{}
	mi := &file_acgc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerGCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerGCResponse) ProtoMessage() {}

func (x *TriggerGCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerGCResponse.ProtoReflect.Descriptor instead.
func (*TriggerGCResponse) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerGCResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *TriggerGCResponse) GetNodesSwept() int32 {
	if x != nil {
		return x.NodesSwept
	}
	return 0
}

func (x *TriggerGCResponse) GetBranchesCompressed() int32 {
	if x != nil {
		return x.BranchesCompressed
	}
	return 0
}

func (x *TriggerGCResponse) GetTokensFreed() int32 {
	if x != nil {
		return x.TokensFreed
	}
	return 0
}

func (x *TriggerGCResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_acgc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{14}
}

func (x *GetMetricsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalEvents          int32                  `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	TotalTurns           int32                  `protobuf:"varint,3,opt,name=total_turns,json=totalTurns,proto3" json:"total_turns,omitempty"`
	GcRuns               int32                  `protobuf:"varint,4,opt,name=gc_runs,json=gcRuns,proto3" json:"gc_runs,omitempty"`
	TotalTokensSaved     int32                  `protobuf:"varint,5,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	AvgReductionPercent  float32                `protobuf:"fixed32,6,opt,name=avg_reduction_percent,json=avgReductionPercent,proto3" json:"avg_reduction_percent,omitempty"`
	BranchesCompressed   int32                  `protobuf:"varint,7,opt,name=branches_compressed,json=branchesCompressed,proto3" json:"branches_compressed,omitempty"`
	RehydrationEvents    int32                  `protobuf:"varint,8,opt,name=rehydration_events,json=rehydrationEvents,proto3" json:"rehydration_events,omitempty"`
	AvgLatencyOverheadMs float32                `protobuf:"fixed32,9,opt,name=avg_latency_overhead_ms,json=avgLatencyOverheadMs,proto3" json:"avg_latency_overhead_ms,omitempty"`
	SessionStartedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=session_started_at,json=sessionStartedAt,proto3" json:"session_started_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_acgc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acgc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_acgc_proto_rawDescGZIP(), []int{15}
}

func (x *GetMetricsResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMetricsResponse) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTurns() int32 {
	if x != nil {
		return x.TotalTurns
	}
	return 0
}

func (x *GetMetricsResponse) GetGcRuns() int32 {
	if x != nil {
		return x.GcRuns
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalTokensSaved() int32 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *GetMetricsResponse) GetAvgReductionPercent() float32 {
	if x != nil {
		return x.AvgReductionPercent
	}
	return 0
}

func (x *GetMetricsResponse) GetBranchesCompressed() int32 {
	if x != nil {
		return x.BranchesCompressed
	}
	return 0
}

func (x *GetMetricsResponse) GetRehydrationEvents() int32 {
	if x != nil {
		return x.RehydrationEvents
	}
	return 0
}

func (x *GetMetricsResponse) GetAvgLatencyOverheadMs() float32 {
	if x != nil {
		return x.AvgLatencyOverheadMs
	}
	return 0
}

func (x *GetMetricsResponse) GetSessionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartedAt
	}
	return nil
}

var File_acgc_proto protoreflect.FileDescriptor

const file_acgc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"acgc.proto\x12\aacgc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\n" +
	"RunRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12!\n" +
	"\fuser_message\x18\x03 \x01(\tR\vuserMessage\x12!\n" +
	"\ftoken_budget\x18\x04 \x01(\x05R\vtokenBudget\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x121\n" +
	"\n" +
	"llm_config\x18\x06 \x01(\v2\x12.acgc.v1.LLMConfigR\tllmConfig\x12C\n" +
	"\x14conversation_history\x18\a \x03(\v2\x10.acgc.v1.MessageR\x13conversationHistory\"\xb2\x01\n" +
	"\tLLMConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\"m\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\"\x8a\x01\n" +
	"\vRunResponse\x12!\n" +
	"\fllm_response\x18\x01 \x01(\tR\vllmResponse\x12*\n" +
	"\x05stats\x18\x02 \x01(\v2\x14.acgc.v1.PromptStatsR\x05stats\x12,\n" +
	"\x12compiled_prompt_id\x18\x03 \x01(\tR\x10compiledPromptId\"\xf6\x02\n" +
	"\vPromptStats\x120\n" +
	"\x14original_token_count\x18\x01 \x01(\x05R\x12originalTokenCount\x120\n" +
	"\x14compiled_token_count\x18\x02 \x01(\x05R\x12compiledTokenCount\x12!\n" +
	"\ftokens_saved\x18\x03 \x01(\x05R\vtokensSaved\x12+\n" +
	"\x11reduction_percent\x18\x04 \x01(\x02R\x10reductionPercent\x12!\n" +
	"\fgc_triggered\x18\x05 \x01(\bR\vgcTriggered\x12\x1b\n" +
	"\tgc_reason\x18\x06 \x01(\tR\bgcReason\x12!\n" +
	"\factive_nodes\x18\a \x01(\x05R\vactiveNodes\x12)\n" +
	"\x10compressed_nodes\x18\b \x01(\x05R\x0fcompressedNodes\x12%\n" +
	"\x0earchived_nodes\x18\t \x01(\x05R\rarchivedNodes\"\x8b\x02\n" +
	"\x13CaptureEventRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.acgc.v1.CaptureEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x14CaptureEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"\x86\x01\n" +
	"\x0fGetStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0einclude_scores\x18\x02 \x01(\bR\rincludeScores\x12-\n" +
	"\x12include_compressed\x18\x03 \x01(\bR\x11includeCompressed\"\xa7\x01\n" +
	"\x10GetStateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.acgc.v1.StateNodeR\x05nodes\x121\n" +
	"\n" +
	"tree_stats\x18\x04 \x01(\v2\x12.acgc.v1.TreeStatsR\ttreeStats\"\xe8\x03\n" +
	"\tStateNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05facts\x18\x06 \x03(\tR\x05facts\x12\x1c\n" +
	"\tdecisions\x18\a \x03(\tR\tdecisions\x12\x1f\n" +
	"\vopen_issues\x18\b \x03(\tR\n" +
	"openIssues\x12\"\n" +
	"\fdependencies\x18\t \x03(\tR\fdependencies\x12$\n" +
	"\x0eraw_event_refs\x18\n" +
	" \x03(\tR\frawEventRefs\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12+\n" +
	"\x06scores\x18\f \x01(\v2\x13.acgc.v1.NodeScoresR\x06scores\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcb\x01\n" +
	"\n" +
	"NodeScores\x12-\n" +
	"\x12semantic_relevance\x18\x01 \x01(\x02R\x11semanticRelevance\x12\x18\n" +
	"\arecency\x18\x02 \x01(\x02R\arecency\x12+\n" +
	"\x11dependency_weight\x18\x03 \x01(\x02R\x10dependencyWeight\x12\x1e\n" +
	"\n" +
	"redundancy\x18\x04 \x01(\x02R\n" +
	"redundancy\x12'\n" +
	"\x0fretention_score\x18\x05 \x01(\x02R\x0eretentionScore\"\xdb\x01\n" +
	"\tTreeStats\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12!\n" +
	"\factive_nodes\x18\x02 \x01(\x05R\vactiveNodes\x12)\n" +
	"\x10compressed_nodes\x18\x03 \x01(\x05R\x0fcompressedNodes\x12%\n" +
	"\x0earchived_nodes\x18\x04 \x01(\x05R\rarchivedNodes\x12\x1b\n" +
	"\tmax_depth\x18\x05 \x01(\x05R\bmaxDepth\x12\x1b\n" +
	"\tmax_width\x18\x06 \x01(\x05R\bmaxWidth\"G\n" +
	"\x10TriggerGCRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xbe\x01\n" +
	"\x11TriggerGCResponse\x12\x1c\n" +
	"\ttriggered\x18\x01 \x01(\bR\ttriggered\x12\x1f\n" +
	"\vnodes_swept\x18\x02 \x01(\x05R\n" +
	"nodesSwept\x12/\n" +
	"\x13branches_compressed\x18\x03 \x01(\x05R\x12branchesCompressed\x12!\n" +
	"\ftokens_freed\x18\x04 \x01(\x05R\vtokensFreed\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"2\n" +
	"\x11GetMetricsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd3\x03\n" +
	"\x12GetMetricsResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x05R\vtotalEvents\x12\x1f\n" +
	"\vtotal_turns\x18\x03 \x01(\x05R\n" +
	"totalTurns\x12\x17\n" +
	"\agc_runs\x18\x04 \x01(\x05R\x06gcRuns\x12,\n" +
	"\x12total_tokens_saved\x18\x05 \x01(\x05R\x10totalTokensSaved\x122\n" +
	"\x15avg_reduction_percent\x18\x06 \x01(\x02R\x13avgReductionPercent\x12/\n" +
	"\x13branches_compressed\x18\a \x01(\x05R\x12branchesCompressed\x12-\n" +
	"\x12rehydration_events\x18\b \x01(\x05R\x11rehydrationEvents\x125\n" +
	"\x17avg_latency_overhead_ms\x18\t \x01(\x02R\x14avgLatencyOverheadMs\x12H\n" +
	"\x12session_started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionStartedAt2\xd8\x02\n" +
	"\vACGCService\x120\n" +
	"\x03Run\x12\x13.acgc.v1.RunRequest\x1a\x14.acgc.v1.RunResponse\x12K\n" +
	"\fCaptureEvent\x12\x1c.acgc.v1.CaptureEventRequest\x1a\x1d.acgc.v1.CaptureEventResponse\x12?\n" +
	"\bGetState\x12\x18.acgc.v1.GetStateRequest\x1a\x19.acgc.v1.GetStateResponse\x12B\n" +
	"\tTriggerGC\x12\x19.acgc.v1.TriggerGCRequest\x1a\x1a.acgc.v1.TriggerGCResponse\x12E\n" +
	"\n" +
	"GetMetrics\x12\x1a.acgc.v1.GetMetricsRequest\x1a\x1b.acgc.v1.GetMetricsResponseB.Z,github.com/chandrashekhartata/acgc/api/protob\x06proto3"

var (
	file_acgc_proto_rawDescOnce sync.Once
	file_acgc_proto_rawDescData []byte
)

func file_acgc_proto_rawDescGZIP() []byte {
	file_acgc_proto_rawDescOnce.Do(func() {
		file_acgc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acgc_proto_rawDesc), len(file_acgc_proto_rawDesc)))
	})
	return file_acgc_proto_rawDescData
}

var file_acgc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_acgc_proto_goTypes = []any{
	(*RunRequest)(nil),            // 0: acgc.v1.RunRequest
	(*LLMConfig)(nil),             // 1: acgc.v1.LLMConfig
	(*Message)(nil),               // 2: acgc.v1.Message
	(*RunResponse)(nil),           // 3: acgc.v1.RunResponse
	(*PromptStats)(nil),           // 4: acgc.v1.PromptStats
	(*CaptureEventRequest)(nil),   // 5: acgc.v1.CaptureEventRequest
	(*CaptureEventResponse)(nil),  // 6: acgc.v1.CaptureEventResponse
	(*GetStateRequest)(nil),       // 7: acgc.v1.GetStateRequest
	(*GetStateResponse)(nil),      // 8: acgc.v1.GetStateResponse
	(*StateNode)(nil),             // 9: acgc.v1.StateNode
	(*NodeScores)(nil),            // 10: acgc.v1.NodeScores
	(*TreeStats)(nil),             // 11: acgc.v1.TreeStats
	(*TriggerGCRequest)(nil),      // 12: acgc.v1.TriggerGCRequest
	(*TriggerGCResponse)(nil),     // 13: acgc.v1.TriggerGCResponse
	(*GetMetricsRequest)(nil),     // 14: acgc.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),    // 15: acgc.v1.GetMetricsResponse
	nil,                           // 16: acgc.v1.CaptureEventRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_acgc_proto_depIdxs = []int32{
	1,  // 0: acgc.v1.RunRequest.llm_config:type_name -> acgc.v1.LLMConfig
	2,  // 1: acgc.v1.RunRequest.conversation_history:type_name -> acgc.v1.Message
	4,  // 2: acgc.v1.RunResponse.stats:type_name -> acgc.v1.PromptStats
	16, // 3: acgc.v1.CaptureEventRequest.metadata:type_name -> acgc.v1.CaptureEventRequest.MetadataEntry
	9,  // 4: acgc.v1.GetStateResponse.nodes:type_name -> acgc.v1.StateNode
	11, // 5: acgc.v1.GetStateResponse.tree_stats:type_name -> acgc.v1.TreeStats
	10, // 6: acgc.v1.StateNode.scores:type_name -> acgc.v1.NodeScores
	17, // 7: acgc.v1.StateNode.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: acgc.v1.StateNode.updated_at:type_name -> google.protobuf.Timestamp
	17, // 9: acgc.v1.GetMetricsResponse.session_started_at:type_name -> google.protobuf.Timestamp
	0,  // 10: acgc.v1.ACGCService.Run:input_type -> acgc.v1.RunRequest
	5,  // 11: acgc.v1.ACGCService.CaptureEvent:input_type -> acgc.v1.CaptureEventRequest
	7,  // 12: acgc.v1.ACGCService.GetState:input_type -> acgc.v1.GetStateRequest
	12, // 13: acgc.v1.ACGCService.TriggerGC:input_type -> acgc.v1.TriggerGCRequest
	14, // 14: acgc.v1.ACGCService.GetMetrics:input_type -> acgc.v1.GetMetricsRequest
	3,  // 15: acgc.v1.ACGCService.Run:output_type -> acgc.v1.RunResponse
	6,  // 16: acgc.v1.ACGCService.CaptureEvent:output_type -> acgc.v1.CaptureEventResponse
	8,  // 17: acgc.v1.ACGCService.GetState:output_type -> acgc.v1.GetStateResponse
	13, // 18: acgc.v1.ACGCService.TriggerGC:output_type -> acgc.v1.TriggerGCResponse
	15, // 19: acgc.v1.ACGCService.GetMetrics:output_type -> acgc.v1.GetMetricsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_acgc_proto_init() }
func file_acgc_proto_init() {
	if File_acgc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acgc_proto_rawDesc), len(file_acgc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acgc_proto_goTypes,
		DependencyIndexes: file_acgc_proto_depIdxs,
		MessageInfos:      file_acgc_proto_msgTypes,
	}.Build()
	File_acgc_proto = out.File
	file_acgc_proto_goTypes = nil
	file_acgc_proto_depIdxs = nil
}
